func main():
    try:
        try:
            raise ValueError()
        except ValueError:
            print("ValueError")
    finally:
        print("finally")
